version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Makassar"
    open-pull-requests-limit: 5
    groups:
      npm-security-maintenance:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:20"
      timezone: "Asia/Makassar"
    open-pull-requests-limit: 5
    groups:
      github-actions-maintenance:
        patterns:
          - "*"
