const STORAGE_KEY='star-dataset-v2';
const oldKey='ral-input-v1';
let state=loadState()||{headers:['Ulangan','Perlakuan','Respons'],rows:Array.from({length:20},()=>['','','']),design:null};
const $=id=>document.getElementById(id);
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))}catch(e){return null}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if($('saveStatus'))$('saveStatus').textContent='Tersimpan otomatis · '+new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function num(v){if(v===null||v===undefined||String(v).trim()==='')return null;const n=Number(String(v).trim().replace(',','.'));return Number.isFinite(n)?n:null}
function normalize(){state.headers=Array.isArray(state.headers)&&state.headers.length?state.headers.map((x,i)=>String(x||`V${i+1}`)):['V1'];state.rows=Array.isArray(state.rows)?state.rows:[];state.rows=state.rows.map(r=>{r=Array.isArray(r)?r:[];while(r.length<state.headers.length)r.push('');return r.slice(0,state.headers.length)});if(!state.rows.length)state.rows=Array.from({length:20},()=>Array(state.headers.length).fill(''))}
function render(){normalize();const h=[];h.push('<table class="sheet raw-sheet"><thead><tr><th class="corner">#</th>');state.headers.forEach((v,j)=>h.push(`<th class="var-head"><input class="header-input" data-head="${j}" value="${esc(v)}" title="Nama variabel"></th>`));h.push('</tr></thead><tbody>');state.rows.forEach((row,i)=>{h.push(`<tr><td class="row-number">${i+1}</td>`);state.headers.forEach((_,j)=>h.push(`<td><input class="cell" inputmode="text" data-i="${i}" data-j="${j}" value="${esc(row[j])}" aria-label="Baris ${i+1}, kolom ${j+1}"></td>`));h.push('</tr>')});h.push('</tbody></table>');$('tableWrap').innerHTML=h.join('');
 document.querySelectorAll('.cell').forEach(el=>{el.addEventListener('input',()=>{state.rows[+el.dataset.i][+el.dataset.j]=el.value;updateSummary();saveState()});el.addEventListener('keydown',navigate)});
 document.querySelectorAll('.header-input').forEach(el=>el.addEventListener('input',()=>{state.headers[+el.dataset.head]=el.value||`V${+el.dataset.head+1}`;saveState();updateSummary()}));
 updateSummary();updateDesignStatus();saveState();
}
function navigate(e){if(!['Tab','Enter','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const cells=[...document.querySelectorAll('.cell')],idx=cells.indexOf(e.currentTarget),i=+e.currentTarget.dataset.i,j=+e.currentTarget.dataset.j;let ni=i,nj=j;if(e.key==='Tab'){const p=idx+(e.shiftKey?-1:1);if(cells[p])cells[p].focus();return}if(e.key==='Enter')ni=Math.max(0,Math.min(state.rows.length-1,i+(e.shiftKey?-1:1)));if(e.key==='ArrowUp')ni=Math.max(0,i-1);if(e.key==='ArrowDown')ni=Math.min(state.rows.length-1,i+1);if(e.key==='ArrowLeft')nj=Math.max(0,j-1);if(e.key==='ArrowRight')nj=Math.min(state.headers.length-1,j+1);document.querySelector(`.cell[data-i="${ni}"][data-j="${nj}"]`)?.focus()}
function addRow(){state.rows.push(Array(state.headers.length).fill(''));render();focusLastRow()}
function addColumn(){state.headers.push(`V${state.headers.length+1}`);state.rows.forEach(r=>r.push(''));render();document.querySelector(`.header-input[data-head="${state.headers.length-1}"]`)?.focus()}
function focusLastRow(){document.querySelector(`.cell[data-i="${state.rows.length-1}"][data-j="0"]`)?.focus()}
function newData(){if(confirm('Buat Data Sheet baru? Data yang tersimpan di sheet ini akan dihapus.')){state={headers:['Ulangan','Perlakuan','Respons'],rows:Array.from({length:20},()=>['','','']),design:null};render()}}
function clearData(){if(confirm('Kosongkan seluruh isi data?')){state.rows=Array.from({length:Math.max(20,state.rows.length)},()=>Array(state.headers.length).fill(''));state.design=null;render()}}
function downloadCsv(){const rows=[state.headers,...state.rows];const csv='\ufeff'+rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='data-penelitian.csv';a.click();URL.revokeObjectURL(a.href)}
function updateSummary(){const filled=state.rows.reduce((n,r)=>n+r.filter(v=>String(v??'').trim()!=='').length,0);const numeric=state.rows.reduce((n,r)=>n+r.filter(v=>num(v)!==null).length,0);$('summary').innerHTML=`<div class="summary-item"><div class="name">Variabel</div><div class="value">${state.headers.length}</div></div><div class="summary-item"><div class="name">Baris</div><div class="value">${state.rows.length}</div></div><div class="summary-item"><div class="name">Sel terisi</div><div class="value">${filled}</div></div><div class="summary-item"><div class="name">Numerik</div><div class="value">${numeric}</div></div>`}
function updateDesignStatus(){const d=state.design;if(!d){$('designStatus').textContent='Design: Data mentah';$('statusDesign').textContent='Design: Data mentah';return}$('designStatus').textContent=`Design: RAL · ${state.headers[d.treatment]||'—'} → ${state.headers[d.response]||'—'}`;$('statusDesign').textContent=$('designStatus').textContent}
function showRalDialog(){normalize();let old=state.design||{};const opts=state.headers.map((h,i)=>`<option value="${i}">${esc(h)}</option>`).join('');const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.innerHTML=`<div class="modal"><div class="modal-title">Rancangan Acak Lengkap (RAL)</div><div class="modal-body"><p>Pilih kolom dari data mentah untuk mendefinisikan model RAL.</p><label>Kolom perlakuan<select id="ralTreatment">${opts}</select></label><label>Kolom ulangan <select id="ralRep"><option value="-1">Tidak digunakan</option>${opts}</select></label><label>Kolom respons / variabel Y<select id="ralResponse">${opts}</select></label><div class="modal-note">Untuk ANOVA RAL, setiap perlakuan harus memiliki pengamatan respons yang sesuai. Kolom ulangan digunakan sebagai informasi struktur data dan pemeriksaan keseimbangan.</div></div><div class="modal-actions"><button class="sheet-btn" id="ralCancel">Batal</button><button class="sheet-btn primary" id="ralApply">Terapkan RAL</button></div></div>`;document.body.appendChild(overlay);if(old.treatment!==undefined)$('ralTreatment').value=old.treatment;if(old.rep!==undefined)$('ralRep').value=old.rep;if(old.response!==undefined)$('ralResponse').value=old.response;$('ralCancel').onclick=()=>overlay.remove();$('ralApply').onclick=()=>{state.design={treatment:+$('ralTreatment').value,rep:+$('ralRep').value,response:+$('ralResponse').value};saveState();updateDesignStatus();overlay.remove();alert(`Desain RAL diterapkan.\nPerlakuan: ${state.headers[state.design.treatment]}\nRespons: ${state.headers[state.design.response]}`)}}
function prepareRal(){if(!state.design){showRalDialog();return false}const d=state.design,groups=new Map(),responseName=state.headers[d.response]||'Respons';state.rows.forEach(r=>{const tr=String(r[d.treatment]??'').trim(),rv=num(r[d.response]);if(tr!==''&&rv!==null){if(!groups.has(tr))groups.set(tr,[]);groups.get(tr).push(rv)}});if(groups.size<2){alert('ERROR: RAL memerlukan minimal dua perlakuan dengan data respons numerik.');return false}const labels=[...groups.keys()],maxRep=Math.max(...labels.map(k=>groups.get(k).length));state.ralData={variable:responseName,unit:'',treatments:labels.length,reps:maxRep,data:labels.map(label=>Object.assign(groups.get(label).slice(),{label}))};saveState();return true}
function analyzeRal(){try{if(prepareRal())window.location.href='analysis.html'}catch(e){console.error(e);alert('ERROR saat menyiapkan Analisis RAL:\n\n'+e.message)}}
document.addEventListener('paste',e=>{const target=e.target.closest('.cell');if(!target)return;const text=(e.clipboardData||window.clipboardData).getData('text');if(!text||!/[\t\n]/.test(text))return;e.preventDefault();const rows=text.replace(/\r/g,'').split('\n').filter(r=>r.length).map(r=>r.split('\t'));const si=+target.dataset.i,sj=+target.dataset.j;const maxCols=Math.max(...rows.map(r=>r.length));if(si===0&&sj===0){if(rows[0]){state.headers=rows[0].map((v,j)=>String(v).trim()||`V${j+1}`);state.rows=rows.slice(1).map(r=>{while(r.length<state.headers.length)r.push('');return r.slice(0,state.headers.length)});while(state.rows.length<20)state.rows.push(Array(state.headers.length).fill(''));state.design=null;render();document.querySelector('.cell')?.focus();return}}rows.forEach((r,ri)=>r.forEach((value,cj)=>{const i=si+ri,j=sj+cj;if(i>=state.rows.length)state.rows.push(Array(state.headers.length).fill(''));if(j>=state.headers.length){state.headers.push(`V${j+1}`);state.rows.forEach(row=>{while(row.length<state.headers.length)row.push('')})}state.rows[i][j]=value.trim()});render();document.querySelector(`.cell[data-i="${si}"][data-j="${sj}"]`)?.focus()});
$('addRowBtn').onclick=addRow;$('addColBtn').onclick=addColumn;$('addRowTop').onclick=addRow;$('addColTop').onclick=addColumn;$('newDataTop').onclick=newData;$('clearDataSheet').onclick=clearData;$('clearDataTop').onclick=clearData;$('downloadCsvSheet').onclick=downloadCsv;$('downloadCsvTop').onclick=downloadCsv;$('ralSetupBtn').onclick=showRalDialog;$('ralSetupBottom').onclick=showRalDialog;$('ralTop').onclick=showRalDialog;$('analyzeRal').onclick=analyzeRal;$('analyzeTop').onclick=analyzeRal;$('menuRal').onclick=e=>{e.preventDefault();showRalDialog()};$('menuNewData').onclick=e=>{e.preventDefault();newData()};$('menuAddRow').onclick=e=>{e.preventDefault();addRow()};$('menuAddColumn').onclick=e=>{e.preventDefault();addColumn()};$('menuImport').onclick=e=>{e.preventDefault();document.querySelector('.cell')?.focus();alert('Salin tabel dari Excel, lalu klik sel A1 dan tekan Ctrl+V.')};
render();
