const STORAGE_KEY='ral-input-v1';
let state=loadState()||{variable:'Variabel pengamatan',unit:'',treatments:5,reps:4,data:[]};
const $=id=>document.getElementById(id);
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))}catch(e){return null}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('saveStatus').textContent='Tersimpan otomatis · '+new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'})}
function normalize(){state.treatments=Math.max(1,Math.min(50,Number(state.treatments)||1));state.reps=Math.max(1,Math.min(100,Number(state.reps)||1));while(state.data.length<state.treatments)state.data.push([]);state.data=state.data.slice(0,state.treatments);state.data=state.data.map((r,i)=>{r=r||[];while(r.length<state.reps)r.push('');r.label=r.label||'P'+(i+1);return r.slice(0,state.reps)})}
function render(){normalize();$('variableName').value=state.variable;$('unitName').value=state.unit;$('treatmentCount').value=state.treatments;$('repCount').value=state.reps;let h='<table class="sheet"><thead><tr><th class="corner">#</th><th class="row-label">Perlakuan</th>';for(let j=0;j<state.reps;j++)h+=`<th>U${j+1}</th>`;h+='<th>Rerata</th><th></th></tr></thead><tbody>';for(let i=0;i<state.treatments;i++){h+=`<tr><td class="row-number">${i+1}</td><td class="row-label"><input class="label-input" data-label="${i}" value="${esc(state.data[i].label||'P'+(i+1))}"></td>`;for(let j=0;j<state.reps;j++)h+=`<td><input class="cell" inputmode="decimal" data-i="${i}" data-j="${j}" value="${esc(state.data[i][j]??'')}" aria-label="P${i+1} U${j+1}"></td>`;h+=`<td class="mean" id="mean-${i}">—</td><td><button class="remove" data-remove="${i}" title="Hapus perlakuan">×</button></td></tr>`}h+='</tbody></table>';$('tableWrap').innerHTML=h;document.querySelectorAll('.cell').forEach(el=>{el.addEventListener('input',()=>{state.data[+el.dataset.i][+el.dataset.j]=el.value;updateSummary();saveState()});el.addEventListener('keydown',navigate)});document.querySelectorAll('.label-input').forEach(el=>el.addEventListener('input',()=>{state.data[+el.dataset.label].label=el.value;saveState()}));document.querySelectorAll('[data-remove]').forEach(el=>el.addEventListener('click',()=>removeTreatment(+el.dataset.remove)));updateSummary();saveState()}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function num(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).trim().replace(',','.'));return Number.isFinite(n)?n:null}
function updateSummary(){const items=[];for(let i=0;i<state.treatments;i++){const vals=state.data[i].slice(0,state.reps).map(num).filter(v=>v!==null);const mean=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;const el=$('mean-'+i);if(el)el.textContent=mean===null?'—':mean.toFixed(3);items.push({label:state.data[i].label||'P'+(i+1),mean,n:vals.length})}$('summary').innerHTML=items.map(x=>`<div class="summary-item"><div class="name">${esc(x.label)} · n=${x.n}</div><div class="value">${x.mean===null?'—':x.mean.toFixed(3)}</div></div>`).join('')}
function navigate(e){if(!['Tab','Enter','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;const cells=[...document.querySelectorAll('.cell')],idx=cells.indexOf(e.currentTarget),i=+e.currentTarget.dataset.i,j=+e.currentTarget.dataset.j;if(e.key==='Tab'){e.preventDefault();const p=idx+(e.shiftKey?-1:1);if(cells[p])cells[p].focus()}else if(e.key==='Enter'){e.preventDefault();const ni=Math.min(state.treatments-1,i+(e.shiftKey?-1:1));document.querySelector(`.cell[data-i="${ni}"][data-j="${j}"]`)?.focus()}else if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();const ni=Math.max(0,Math.min(state.treatments-1,i+(e.key==='ArrowDown'?1:-1)));document.querySelector(`.cell[data-i="${ni}"][data-j="${j}"]`)?.focus()}else{e.preventDefault();const nj=Math.max(0,Math.min(state.reps-1,j+(e.key==='ArrowRight'?1:-1)));document.querySelector(`.cell[data-i="${i}"][data-j="${nj}"]`)?.focus()}}
function rebuild(t,r){const old=state.data;state.treatments=t;state.reps=r;state.data=Array.from({length:t},(_,i)=>{const row=old[i]||[];return Object.assign(Array.from({length:r},(_,j)=>row[j]??''),{label:row.label||'P'+(i+1)})});render()}
function removeTreatment(i){if(state.treatments<=1)return;state.data.splice(i,1);state.treatments--;render()}
$('applySetup').addEventListener('click',()=>{state.variable=$('variableName').value.trim()||'Variabel pengamatan';state.unit=$('unitName').value.trim();rebuild(Math.max(1,Math.min(50,+$('treatmentCount').value||1)),Math.max(1,Math.min(100,+$('repCount').value||1)))});
$('addTreatment').addEventListener('click',()=>rebuild(state.treatments+1,state.reps));
$('addRep').addEventListener('click',()=>rebuild(state.treatments,state.reps+1));
$('clearData').addEventListener('click',()=>{if(confirm('Kosongkan seluruh nilai pengamatan?')){state.data=Array.from({length:state.treatments},(_,i)=>Object.assign(Array.from({length:state.reps},()=>''),{label:'P'+(i+1)}));render()}});
$('downloadCsv').addEventListener('click',()=>{let rows=[['Perlakuan',...Array.from({length:state.reps},(_,j)=>'U'+(j+1)),'Rerata']];for(let i=0;i<state.treatments;i++){const vals=state.data[i].slice(0,state.reps).map(v=>v??'');const nums=vals.map(num).filter(v=>v!==null);const mean=nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:'';rows.push([state.data[i].label||'P'+(i+1),...vals,mean])}const csv='\ufeff'+rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='data-RAL.csv';a.click();URL.revokeObjectURL(a.href)});
$('analyzeRal').addEventListener('click',()=>{try{normalize();const errors=[];state.data.forEach((row,i)=>{for(let j=0;j<state.reps;j++){const raw=row[j];if(raw===''||raw===null||raw===undefined)errors.push(`P${i+1} U${j+1}: data kosong`);else if(num(raw)===null)errors.push(`P${i+1} U${j+1}: "${raw}" bukan angka`)}});if(errors.length){alert('ERROR: Data RAL belum valid.\n\n'+errors.slice(0,12).join('\n')+(errors.length>12?'\n… dan '+(errors.length-12)+' error lainnya.':''));return}saveState();window.location.href='analysis.html'}catch(e){console.error(e);alert('ERROR saat menjalankan Analisis RAL:\n\n'+e.message)}});
document.addEventListener('paste',e=>{const target=e.target.closest('.cell');if(!target)return;const text=(e.clipboardData||window.clipboardData).getData('text');if(!text||!/[\t\n]/.test(text))return;e.preventDefault();const rows=text.replace(/\r/g,'').split('\n').filter(r=>r.length);const si=+target.dataset.i,sj=+target.dataset.j;rows.forEach((row,ri)=>row.split('\t').forEach((value,cj)=>{const i=si+ri,j=sj+cj;if(i<state.treatments&&j<state.reps)state.data[i][j]=value.trim()}));render();document.querySelector(`.cell[data-i="${si}"][data-j="${sj}"]`)?.focus()});
render();
