/* Design selector shared by the STAR-style data sheet. RAL is the active module. */
(function(){
  const KEY='star-dataset-v2';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return {}}};
  const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
  const headers=()=>{const s=read();return Array.isArray(s.headers)?s.headers:[]};
  const options=(selected=-1,optional=false)=>{const hs=headers();return (optional?'<option value="-1">Tidak digunakan</option>':'')+hs.map((h,i)=>`<option value="${i}" ${i===selected?'selected':''}>${esc(h||`V${i+1}`)}</option>`).join('')};
  function setStatus(){const s=read(),d=s.design;let text='Design: Data mentah';if(d&&d.type==='RAL'){const hs=s.headers||[];text=`Design: RAL · ${hs[d.treatment]||'Perlakuan'} → ${hs[d.response]||'Respons'}`}['designStatus','statusDesign'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=text})}
  function routeAnalysis(){const s=read(),d=s.design;if(!d){alert('ERROR: Tentukan Design terlebih dahulu.');return}if(d.type==='RAL')location.href='ral-analysis.html';else alert('Untuk saat ini, hanya modul RAL yang aktif. Kita selesaikan RAL terlebih dahulu sebelum mengaktifkan rancangan lain.')}
  function openRal(){const s=read(),d=s.design?.type==='RAL'?s.design:{},hs=s.headers||[];if(hs.length<2){alert('ERROR: Data Sheet harus memiliki minimal dua kolom.');return}const ov=document.createElement('div');ov.className='modal-backdrop';ov.innerHTML=`<div class="modal"><div class="modal-title">Rancangan Acak Lengkap (RAL)</div><div class="modal-body"><p>Pilih kolom dari Data Sheet untuk mendefinisikan RAL.</p><label>Kolom perlakuan<select id="ralTreatment">${options(d.treatment??-1)}</select></label><label>Kolom ulangan<select id="ralRep"><option value="-1">Tidak digunakan</option>${options(d.rep??-1)}</select></label><label>Kolom respons / variabel Y<select id="ralResponse">${options(d.response??-1)}</select></label><div class="modal-note">Kolom perlakuan dan respons harus berbeda. Kolom ulangan digunakan untuk pemeriksaan keseimbangan.</div></div><div class="modal-actions"><button class="sheet-btn" id="cancel">Batal</button><button class="sheet-btn primary" id="apply">Terapkan RAL</button></div></div>`;document.body.appendChild(ov);ov.querySelector('#cancel').onclick=()=>ov.remove();ov.querySelector('#apply').onclick=()=>{const treatment=+ov.querySelector('#ralTreatment').value,rep=+ov.querySelector('#ralRep').value,response=+ov.querySelector('#ralResponse').value;if(treatment===response){alert('ERROR: Kolom perlakuan dan respons harus berbeda.');return}s.design={type:'RAL',treatment,rep,response};write(s);setStatus();ov.remove();alert(`Desain RAL diterapkan.\nPerlakuan: ${s.headers[treatment]}\nRespons: ${s.headers[response]}`)}}
  function wire(){const menus=[...document.querySelectorAll('.menu')];const dm=menus.find(m=>String(m.firstChild?.textContent||'').trim()==='Design');if(dm)dm.querySelectorAll('.dropdown a').forEach(a=>{if(a.textContent.includes('RAL'))a.addEventListener('click',e=>{e.preventDefault();openRal()});if(a.textContent.includes('RAK')||a.textContent.includes('Faktorial'))a.addEventListener('click',e=>{e.preventDefault();alert('Modul ini akan diaktifkan setelah RAL selesai.')})});setStatus();['analyzeTop','analyzeRal','menuAnalyzeCurrent'].forEach(id=>{const el=document.getElementById(id);if(el)el.onclick=e=>{if(e)e.preventDefault();routeAnalysis()}})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();window.STARDesign={openRal,setStatus,routeAnalysis};
})();
