/* Design selector for RAL, RAK and Factorial — shared raw-data workflow. */
(function(){
  const KEY='star-dataset-v2';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return {}}};
  const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
  const headers=()=>{const s=read();return Array.isArray(s.headers)?s.headers:[]};
  const options=(selected=-1,optional=false)=>{const hs=headers();return (optional?'<option value="-1">Tidak digunakan</option>':'')+hs.map((h,i)=>`<option value="${i}" ${i===selected?'selected':''}>${esc(h||`V${i+1}`)}</option>`).join('')};
  function setStatus(){const s=read(),d=s.design;let text='Design: Data mentah';if(d){const hs=s.headers||[];if(d.type==='RAK')text=`Design: RAK · ${hs[d.block]||'Blok'} × ${hs[d.treatment]||'Perlakuan'} → ${hs[d.response]||'Respons'}`;else if(d.type==='FAKTORIAL')text=`Design: Faktorial · ${hs[d.factorA]||'Faktor A'} × ${hs[d.factorB]||'Faktor B'} → ${hs[d.response]||'Respons'}`;else if(d.type==='RAL')text=`Design: RAL · ${hs[d.treatment]||'Perlakuan'} → ${hs[d.response]||'Respons'}`}['designStatus','statusDesign'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=text})}
  function open(type){const s=read(),d=s.design||{},hs=s.headers||[];if(hs.length<2){alert('ERROR: Data Sheet harus memiliki minimal dua kolom sebelum rancangan ditentukan.');return}const opts=options;let fields='';if(type==='RAK')fields=`<label>Kolom blok<select id="desBlock">${opts(d.block??-1)}</select></label><label>Kolom perlakuan<select id="desTreatment">${opts(d.treatment??-1)}</select></label><label>Kolom respons / variabel Y<select id="desResponse">${opts(d.response??-1)}</select></label>`;if(type==='FAKTORIAL')fields=`<label>Faktor A<select id="desA">${opts(d.factorA??-1)}</select></label><label>Faktor B<select id="desB">${opts(d.factorB??-1)}</select></label><label>Kolom ulangan / blok<select id="desRep">${opts(d.rep??-1,true)}</select></label><label>Kolom respons / variabel Y<select id="desResponse">${opts(d.response??-1)}</select></label>`;const title=type==='RAK'?'Rancangan Acak Kelompok (RAK)':'Rancangan Faktorial';const note=type==='RAK'?'Pilih satu kolom blok, satu kolom perlakuan, dan satu respons.':'Pilih dua faktor dan satu respons. Kolom ulangan/blok bersifat opsional.';const ov=document.createElement('div');ov.className='modal-backdrop';ov.innerHTML=`<div class="modal"><div class="modal-title">${title}</div><div class="modal-body"><p>${note}</p>${fields}<div class="modal-note">Data tetap berasal dari Data Sheet tengah. Tidak perlu memasukkan data ulang.</div></div><div class="modal-actions"><button class="sheet-btn" id="desCancel">Batal</button><button class="sheet-btn primary" id="desApply">Terapkan</button></div></div>`;document.body.appendChild(ov);ov.querySelector('#desCancel').onclick=()=>ov.remove();ov.querySelector('#desApply').onclick=()=>{const get=id=>{const e=ov.querySelector('#'+id);return e?+e.value:-1};let design={type};if(type==='RAK')design={type,block:get('desBlock'),treatment:get('desTreatment'),response:get('desResponse')};else design={type,factorA:get('desA'),factorB:get('desB'),rep:get('desRep'),response:get('desResponse')};const required=type==='RAK'?[design.block,design.treatment,design.response]:[design.factorA,design.factorB,design.response];if(required.some(x=>x<0)||new Set(required).size!==required.length){alert('ERROR: Pilih kolom yang berbeda dan lengkap untuk rancangan ini.');return}s.design=design;write(s);setStatus();ov.remove();alert(`${title} diterapkan.\nData tetap berada di Data Sheet.`)}}
  function wire(){const menus=[...document.querySelectorAll('.menu')];const designMenu=menus.find(m=>m.firstChild&&String(m.firstChild.textContent).trim()==='Design');if(designMenu){designMenu.querySelectorAll('.dropdown a').forEach(a=>{const t=a.textContent.trim();if(t.includes('RAK'))a.addEventListener('click',e=>{e.preventDefault();open('RAK')});if(t==='Faktorial')a.addEventListener('click',e=>{e.preventDefault();open('FAKTORIAL')})})}setStatus()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();window.STARDesign={open,setStatus};
})();
