import { parseNumber, formatNumber } from './number-format.js';
import { resultActions, installResultExport } from './result-export.js';
import jStat from 'jstat';
(() => {
  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const safeFilename = value => String(value || 'hasil').replace(/[^a-z0-9._-]+/gi,'-');
  function dataset(){const th=[...document.querySelectorAll('#gridWrap .data-grid thead th')].slice(1).map(x=>x.textContent.trim());const rs=[...document.querySelectorAll('#gridWrap .data-grid tbody tr')].map(tr=>[...tr.querySelectorAll('td')].slice(1).map(td=>td.textContent));return {headers:th,rows:rs};}
  function err(msg){const b=$('#ralError');if(b){b.hidden=false;b.textContent='⚠ '+msg;}const s=$('#status');if(s)s.textContent='⚠ '+msg;}
  function clearErr(){const b=$('#ralError');if(b){b.hidden=true;b.textContent='';}}
  const numeric=parseNumber, fmt=formatNumber;
  function fcrit(alpha,d1,d2){try{return jStat.centralF.inv(1-alpha,d1,d2);}catch{return NaN;}}
  function sigLabel(f,f05,f01){if(f===Infinity)return 'sangat nyata';if(!Number.isFinite(f))return '—';if(Number.isFinite(f01)&&f>f01)return 'sangat nyata';if(Number.isFinite(f05)&&f>f05)return 'nyata';return 'tidak nyata';}
  function label(k){let s='';do{s=String.fromCharCode(97+k%26)+s;k=Math.floor(k/26)-1;}while(k>=0);return s;}
  function subset(a,b){for(const v of a)if(!b.has(v))return false;return true;}
  function cleanColumns(cols){const unique=[];for(const c of cols){if(!unique.some(u=>u.size===c.size&&subset(c,u)))unique.push(c);}return unique.filter((c,i)=>!unique.some((d,j)=>i!==j&&c.size<d.size&&subset(c,d)));}
  function compactLetters(means, significant){const n=means.length;let cols=[new Set(Array.from({length:n},(_,i)=>i))];const pairs=[];for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(significant[i][j])pairs.push([i,j,Math.abs(means[i]-means[j])]);pairs.sort((a,b)=>b[2]-a[2]);for(const [i,j] of pairs){const next=[];for(const col of cols){if(col.has(i)&&col.has(j)){const a=new Set(col),b=new Set(col);a.delete(i);b.delete(j);if(a.size)next.push(a);if(b.size)next.push(b);}else next.push(col);}cols=cleanColumns(next);}cols.sort((a,b)=>Math.max(...[...b].map(i=>means[i]))-Math.max(...[...a].map(i=>means[i])));return means.map((_,i)=>cols.map((c,k)=>c.has(i)?label(k):'').join(''));}
  function observationTable(treatments,groups){const maxN=Math.max(...groups.map(g=>g.length));const colTotals=Array.from({length:maxN},(_,j)=>groups.reduce((s,g)=>s+(Number.isFinite(g[j])?g[j]:0),0));const rowTotals=groups.map(g=>g.reduce((s,v)=>s+v,0));const grand=rowTotals.reduce((s,v)=>s+v,0);const totalN=groups.reduce((s,g)=>s+g.length,0);const rows=treatments.map((t,i)=>`<tr><td>${esc(t)}</td>${Array.from({length:maxN},(_,j)=>`<td>${Number.isFinite(groups[i][j])?fmt(groups[i][j],2):'—'}</td>`).join('')}<td>${fmt(rowTotals[i],2)}</td><td>${fmt(rowTotals[i]/groups[i].length,2)}</td></tr>`).join('');return `<table class="result-table observation-table"><thead><tr><th rowspan="2">Perlakuan</th><th colspan="${maxN}">Ulangan</th><th rowspan="2">Total</th><th rowspan="2">Rata-Rata</th></tr><tr>${Array.from({length:maxN},(_,j)=>`<th>${j+1}</th>`).join('')}</tr></thead><tbody>${rows}</tbody><tfoot><tr><td><b>Total</b></td>${colTotals.map(v=>`<td><b>${fmt(v,2)}</b></td>`).join('')}<td><b>${fmt(grand,2)}</b></td><td><b>${fmt(grand/totalN,2)}</b></td></tr></tfoot></table>`;}
  function chartHtml(treatments,means,responseName,no){const max=Math.max(...means);const scale=max>0?max:1;return `<div style="margin:14px 0;border:1px solid #8f8f8f;padding:10px;background:#fff">${treatments.map((t,i)=>`<div style="display:grid;grid-template-columns:minmax(160px,260px) 1fr 70px;gap:8px;align-items:center;margin:5px 0"><div>${esc(t)}</div><div style="height:16px;border-left:1px solid #777;border-bottom:1px solid #ddd"><div style="height:100%;width:${Math.max(0,means[i]/scale*100)}%;background:#5b9bd5"></div></div><div style="text-align:right">${fmt(means[i],2)}</div></div>`).join('')}</div><div style="font-weight:700;margin:4px 0 12px">Gambar ${no}. Rata-Rata ${esc(responseName)} pada Berbagai Perlakuan (deskriptif).</div>`;}
  function ensureBnjOptions(){if($('#ralBnjOptions'))return;const result=$('#ralResult');if(!result)return;const box=document.createElement('div');box.id='ralBnjOptions';box.className='analysis-note';box.style.cssText='margin:14px 0;padding:12px;display:grid;grid-template-columns:1fr 1fr;gap:12px;align-items:end';box.innerHTML='<div><label for="ralAlpha" style="display:block;font-weight:700;margin-bottom:5px">Taraf nyata BNJ (α)</label><select id="ralAlpha"><option value="0.05">0.05 (5%)</option><option value="0.01">0.01 (1%)</option></select></div><div style="font-size:13px;color:#526171"><b>q tabel otomatis.</b> Nilai q dihitung dari α, jumlah perlakuan (k), dan db galat. Urutan hasil selalu mengikuti urutan perlakuan pada data.</div>';box.querySelector('select').addEventListener('change',()=>{result.innerHTML='';});result.parentNode.insertBefore(box,result);}
  function populate(){const d=dataset(),list=$('#ralResponses'),sel=$('#ralTreatment');if(!list||!sel)return;list.innerHTML='';sel.innerHTML='';if(!d.headers.length){list.innerHTML='<div style="padding:10px;color:#777">Tidak ada variabel. Masukkan data terlebih dahulu.</div>';return;}d.headers.forEach((h,i)=>{const lab=document.createElement('label');lab.className='ral-check';lab.innerHTML=`<input type="checkbox" value="${i}"> <span>${esc(h)}</span>`;list.appendChild(lab);const o=document.createElement('option');o.value=i;o.textContent=h;sel.appendChild(o);});}
  function open(){clearErr();populate();ensureBnjOptions();$('#ralResult').innerHTML='';$('#ralModal').classList.add('open');}
  function close(){$('#ralModal').classList.remove('open');}
  function analyze(){
    clearErr();$('#ralResult').innerHTML='';const d=dataset(),selected=[...document.querySelectorAll('#ralResponses input:checked')].map(x=>Number(x.value)),ti=Number($('#ralTreatment').value),alpha=Number($('#ralAlpha')?.value);
    if(!selected.length)return err('Pilih minimal satu peubah respons.');if(!Number.isInteger(ti))return err('Pilih peubah perlakuan.');if(selected.includes(ti))return err('Peubah perlakuan tidak boleh dipilih sebagai respons.');if(![0.05,0.01].includes(alpha))return err('Pilih taraf nyata 0.05 atau 0.01.');if(d.rows.length<2)return err('Dataset belum memiliki cukup observasi.');
    const treatments=[...new Set(d.rows.map(r=>String(r[ti]??'').trim()).filter(Boolean))];if(treatments.length<2)return err('RAL memerlukan sedikitnya dua taraf perlakuan.');let html='',tableNo=1,figureNo=1;
    for(const yi of selected){
      const responseName=d.headers[yi];const obs=[];for(const [rowIndex,r] of d.rows.entries()){const t=String(r[ti]??'').trim(),y=numeric(r[yi]);if(t!==''&&!Number.isFinite(y))return err(`Angka pada baris ${rowIndex+1}, kolom ${responseName} tidak valid atau kosong. Periksa Pengaturan angka.`);if(t!==''&&Number.isFinite(y))obs.push({t,y});}
      const groups=treatments.map(t=>obs.filter(o=>o.t===t).map(o=>o.y));if(obs.length<2||groups.some(g=>!g.length)){html+=`<section class="ral-result-block analysis-result" data-export-scope><h4>${esc(responseName)}</h4><div class="analysis-note">Data numerik tidak lengkap untuk semua taraf perlakuan.</div></section>`;continue;}
      const N=obs.length,a=groups.length,grand=obs.reduce((s,o)=>s+o.y,0)/N,meanValues=groups.map(g=>g.reduce((s,x)=>s+x,0)/g.length);const ssT=groups.reduce((s,g)=>s+g.length*(g.reduce((u,v)=>u+v,0)/g.length-grand)**2,0),ssTot=obs.reduce((s,o)=>s+(o.y-grand)**2,0),ssE=groups.reduce((sum,g,i)=>sum+g.reduce((subtotal,y)=>subtotal+(y-meanValues[i])**2,0),0),dfT=a-1,dfE=N-a,msT=ssT/dfT,msE=ssE/dfE,f=msE>0?msT/msE:Infinity;
      if(dfE<2||!Number.isFinite(msE)||msE<=0){html+=`<section class="ral-result-block analysis-result" data-export-scope><h4>${esc(responseName)}</h4>${resultActions(`RAL-${safeFilename(responseName)}`)}<div class="analysis-note">Analisis memerlukan db galat minimal 2 dan KT galat positif.</div></section>`;continue;}
      const f05=fcrit(0.05,dfT,dfE),f01=fcrit(0.01,dfT,dfE),labelSig=sigLabel(f,f05,f01),selectedF=alpha===0.01?f01:f05,isSignificant=f>selectedF;const kk=Math.sqrt(msE)/Math.abs(grand)*100;let q=NaN;try{q=jStat.tukey.inv(1-alpha,a,dfE);}catch{}
      let notations=Array(a).fill(''),bnjHtml='';if(isSignificant){if(!Number.isFinite(q)||q<=0)return err(`q tabel tidak dapat dihitung untuk ${responseName}.`);const significant=Array.from({length:a},()=>Array(a).fill(false));for(let i=0;i<a;i++)for(let j=i+1;j<a;j++){const se=Math.sqrt(msE/2*(1/groups[i].length+1/groups[j].length));significant[i][j]=significant[j][i]=Math.abs(meanValues[i]-meanValues[j])>q*se;}notations=compactLetters(meanValues,significant);const equalN=groups.every(g=>g.length===groups[0].length),se=equalN?Math.sqrt(msE/groups[0].length):NaN,hsd=equalN?q*se:NaN;bnjHtml=`<div style="font-weight:700;margin:12px 0 4px">UJI LANJUT — BNJ ${alpha*100}%</div><table class="result-table"><thead><tr><th>q tabel</th><th>SE</th><th>Nilai BNJ</th></tr></thead><tbody><tr><td>${fmt(q,3)}</td><td>${equalN?fmt(se,6):'Tukey–Kramer'}</td><td>${equalN?fmt(hsd,6):'Tukey–Kramer'}</td></tr></tbody></table>`;}
      const obsNo=tableNo++,anovaNo=tableNo++,meanNo=tableNo++;const means=treatments.map((t,i)=>`<tr><td>${esc(t)}</td><td class="posthoc-value">${fmt(meanValues[i],2)}${notations[i]?`<sup>${esc(notations[i])}</sup>`:''}</td></tr>`).join('');const comparison=labelSig==='sangat nyata'?`F. Hitung (${fmt(f,2)}) lebih besar daripada F. Tabel 0.05 (${fmt(f05,2)}) dan F. Tabel 0.01 (${fmt(f01,2)})`:labelSig==='nyata'?`F. Hitung (${fmt(f,2)}) lebih besar daripada F. Tabel 0.05 (${fmt(f05,2)}), tetapi lebih kecil atau sama dengan F. Tabel 0.01 (${fmt(f01,2)})`:`F. Hitung (${fmt(f,2)}) lebih kecil atau sama dengan F. Tabel 0.05 (${fmt(f05,2)})`;
      const ordered=meanValues.map((m,i)=>({m,i})).sort((x,y)=>y.m-x.m),hi=ordered[0],lo=ordered[ordered.length-1];const meanNarr=isSignificant?`Berdasarkan Tabel ${meanNo}, perlakuan <b>${esc(treatments[hi.i])}</b> memberikan rata-rata ${esc(responseName)} tertinggi sebesar <b>${fmt(hi.m,2)}${notations[hi.i]?`<sup>${esc(notations[hi.i])}</sup>`:''}</b>, sedangkan <b>${esc(treatments[lo.i])}</b> memberikan rata-rata terendah sebesar <b>${fmt(lo.m,2)}${notations[lo.i]?`<sup>${esc(notations[lo.i])}</sup>`:''}</b>. Huruf superscript yang sama menunjukkan tidak berbeda nyata menurut BNJ ${alpha*100}%.`:`Berdasarkan Tabel ${meanNo}, secara deskriptif perlakuan <b>${esc(treatments[hi.i])}</b> mempunyai rata-rata ${esc(responseName)} tertinggi sebesar <b>${fmt(hi.m,2)}</b>, sedangkan <b>${esc(treatments[lo.i])}</b> mempunyai rata-rata terendah sebesar <b>${fmt(lo.m,2)}</b>. Perbedaan tersebut tidak dapat dinyatakan sebagai perbedaan akibat perlakuan karena sidik ragam tidak nyata.`;
      html+=`<section class="ral-result-block analysis-result" data-export-scope><h4>${esc(responseName)}</h4>${resultActions(`RAL-${safeFilename(responseName)}`)}<div style="font-weight:700;margin:10px 0 4px">Tabel ${obsNo}. Data Pengamatan ${esc(responseName)} pada Berbagai Perlakuan</div>${observationTable(treatments,groups)}<div style="font-weight:700;margin:12px 0 4px">Tabel ${anovaNo}. Sidik Ragam ${esc(responseName)}</div><table class="result-table"><thead><tr><th>SK</th><th>db</th><th>JK</th><th>KT</th><th>F. Hitung</th><th>F. Tabel 0.05</th><th>F. Tabel 0.01</th></tr></thead><tbody><tr><td>Perlakuan</td><td>${dfT}</td><td>${fmt(ssT)}</td><td>${fmt(msT)}</td><td>${fmt(f)}</td><td>${fmt(f05,2)}</td><td>${fmt(f01,2)}</td></tr><tr><td>Galat</td><td>${dfE}</td><td>${fmt(ssE)}</td><td>${fmt(msE)}</td><td>—</td><td>—</td><td>—</td></tr><tr><td>Total</td><td>${N-1}</td><td>${fmt(ssTot)}</td><td>—</td><td>—</td><td>—</td><td>—</td></tr></tbody></table><div class="analysis-note">Berdasarkan Tabel ${anovaNo}, perlakuan <b>${labelSig}</b> terhadap ${esc(responseName)} karena ${comparison}.<br><b>KK = ${fmt(kk,2)}%</b></div>${bnjHtml}<div style="font-weight:700;margin:12px 0 4px">Tabel ${meanNo}. Rata-Rata ${esc(responseName)} pada Berbagai Perlakuan${isSignificant?'':' (Deskriptif)'}</div><table class="result-table posthoc-table"><thead><tr><th>Perlakuan</th><th>${esc(responseName)}</th></tr></thead><tbody>${means}</tbody></table><div class="analysis-note">${meanNarr}</div>${isSignificant?'':chartHtml(treatments,meanValues,responseName,figureNo++)}</section>`;
    }
    $('#ralResult').innerHTML=html;
  }
  function bind(){installResultExport();[...document.querySelectorAll('[data-menu="Analyze"],[data-mobile="Analyze"]')].forEach(btn=>{const clone=btn.cloneNode(true);btn.replaceWith(clone);clone.addEventListener('click',e=>{e.preventDefault();open();});});$('#closeRal')?.addEventListener('click',close);$('#closeRal2')?.addEventListener('click',close);$('#runRal')?.addEventListener('click',analyze);$('#ralModal')?.addEventListener('click',e=>{if(e.target.id==='ralModal')close();});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,50));else setTimeout(bind,50);
})();
